import { t } from '@shared/i18n'
import type { LabArtifact, LabCampaign, LabEvidenceSelector, LabHypothesisEvidence, LabHypothesisSet, LabHypothesisSetInput, LabSource } from '@shared/research-lab'

export interface HypothesisEvidenceOption { value: LabEvidenceSelector; label: string }
export const selectorKey = (value: LabEvidenceSelector): string => value.kind === 'source' ? `source:${value.source_id}` : value.kind === 'observation' ? `observation:${value.run_id}` : 'input'
const selector = (value: LabEvidenceSelector): LabEvidenceSelector => value.kind === 'source' ? { kind: 'source', source_id: value.source_id } : value.kind === 'observation' ? { kind: 'observation', run_id: value.run_id } : { kind: 'input' }
const candidate = (statement = '') => ({ id: `h-${crypto.randomUUID()}`, statement, assumptions: [], scope: '', supporting_evidence: [], opposing_evidence: [], predictions: [''], weakening_conditions: [''] })
export const newHypothesisSet = (statement = ''): LabHypothesisSetInput => ({ candidates: [candidate(statement)], open_alternative: '' })
export const editableHypothesisSet = (value: LabHypothesisSet): LabHypothesisSetInput => ({ open_alternative: value.open_alternative, candidates: value.candidates.map(item => ({ id: item.id, statement: item.statement, assumptions: [...item.assumptions], scope: item.scope, predictions: [...item.predictions], weakening_conditions: [...item.weakening_conditions], supporting_evidence: item.supporting_evidence.map(selector), opposing_evidence: item.opposing_evidence.map(selector) })) })
export function hypothesisEvidenceOptions(sources: Pick<LabSource, 'id' | 'title'>[], campaign?: LabCampaign | null): HypothesisEvidenceOption[] {
  const rounds = [...(campaign?.rounds.map(round => ({ index: round.index, run_id: round.run.id })) ?? []), ...(campaign?.omitted_rounds ?? [])]
  return [{ value: { kind: 'input' }, label: t('researchLab.hypotheses.input') }, ...sources.map(source => ({ value: { kind: 'source' as const, source_id: source.id }, label: `${t('researchLab.hypotheses.source')}: ${source.title || source.id}` })), ...[...new Map(rounds.map(round => [round.run_id, round])).values()].sort((a, b) => a.index - b.index).map(round => ({ value: { kind: 'observation' as const, run_id: round.run_id }, label: t('researchLab.hypotheses.observation', { round: round.index }) }))]
}
export function validateHypothesisInput(value: LabHypothesisSetInput, options: HypothesisEvidenceOption[]): LabHypothesisSetInput {
  const validText = (text: string, limit: number, required = true) => typeof text === 'string' && (!required || !!text.trim()) && new TextEncoder().encode(text).length <= limit
  const available = new Set(options.map(option => selectorKey(option.value)))
  const result = { ...value, candidates: value.candidates.map(item => ({ ...item, assumptions: item.assumptions.filter(line => line.trim()), predictions: item.predictions.filter(line => line.trim()), weakening_conditions: item.weakening_conditions.filter(line => line.trim()) })) }
  if (!validText(result.open_alternative, 2000) || result.candidates.length < 1 || result.candidates.length > 4 || new Set(result.candidates.map(item => item.id)).size !== result.candidates.length || result.candidates.some(item => !/^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$/.test(item.id) || !validText(item.statement, 4000) || !validText(item.scope, 2000) || item.assumptions.length > 8 || item.assumptions.some(line => !validText(line, 1000)) || [item.predictions, item.weakening_conditions].some(lines => lines.length < 1 || lines.length > 6 || lines.some(line => !validText(line, 1000))) || [item.supporting_evidence, item.opposing_evidence].some(refs => refs.length > 8 || new Set(refs.map(selectorKey)).size !== refs.length || refs.some(ref => !available.has(selectorKey(ref)))) ) || new TextEncoder().encode(JSON.stringify(result)).length > 65536) throw new Error(t('researchLab.hypotheses.validation'))
  return result
}

export function HypothesisEditor({ value, onChange, options, disabled, initialStatement = '' }: { value: LabHypothesisSetInput | null; onChange: (value: LabHypothesisSetInput | null) => void; options: HypothesisEvidenceOption[]; disabled: boolean; initialStatement?: string }) {
  const edit = (index: number, patch: Partial<LabHypothesisSetInput['candidates'][number]>) => value && onChange({ ...value, candidates: value.candidates.map((item, i) => i === index ? { ...item, ...patch } : item) })
  return <div className="research-hypotheses-editor"><p className="idea-lab-note">{t('researchLab.hypotheses.notice')}</p>
    <label className="idea-lab-pick"><input type="checkbox" disabled={disabled} checked={!!value} onChange={event => onChange(event.target.checked ? newHypothesisSet(initialStatement) : null)} />{t('researchLab.hypotheses.enable')}</label>
    {value && <>{value.candidates.map((item, index) => <fieldset className="idea-lab-source" key={item.id}><legend>{t('researchLab.hypotheses.candidate', { count: index + 1 })}</legend>
      <label>{t('researchLab.hypotheses.statement')}<textarea disabled={disabled} value={item.statement} onChange={event => edit(index, { statement: event.target.value })} /></label>
      <label>{t('researchLab.hypotheses.scope')}<textarea disabled={disabled} value={item.scope} onChange={event => edit(index, { scope: event.target.value })} /></label>
      {(['assumptions', 'predictions', 'weakening_conditions'] as const).map(field => <label key={field}>{t(`researchLab.hypotheses.${field}`)}<textarea disabled={disabled} value={item[field].join('\n')} onChange={event => edit(index, { [field]: event.target.value.split('\n') })} /></label>)}
      {(['supporting_evidence', 'opposing_evidence'] as const).map(field => { const choices = [...options, ...item[field].filter(ref => !options.some(option => selectorKey(option.value) === selectorKey(ref))).map(ref => ({ value: ref, label: t('researchLab.hypotheses.unavailableRef') }))]; return <details key={field}><summary>{t(`researchLab.hypotheses.${field}`)} ({item[field].length})</summary><p className="idea-lab-note">{t('researchLab.hypotheses.evidenceNotice')}</p>{choices.map(option => <label className="idea-lab-pick" key={selectorKey(option.value)}><input type="checkbox" disabled={disabled} checked={item[field].some(ref => selectorKey(ref) === selectorKey(option.value))} onChange={event => edit(index, { [field]: event.target.checked ? [...item[field], option.value] : item[field].filter(ref => selectorKey(ref) !== selectorKey(option.value)) })} />{option.label}</label>)}</details> })}
      <button className="quiet-button" disabled={disabled || value.candidates.length === 1} onClick={() => onChange({ ...value, candidates: value.candidates.filter((_, i) => i !== index) })}>{t('researchLab.hypotheses.remove')}</button>
    </fieldset>)}<button className="quiet-button" disabled={disabled || value.candidates.length >= 4} onClick={() => onChange({ ...value, candidates: [...value.candidates, candidate()] })}>{t('researchLab.hypotheses.add')}</button>
    <label>{t('researchLab.hypotheses.openAlternative')}<textarea disabled={disabled} value={value.open_alternative} onChange={event => onChange({ ...value, open_alternative: event.target.value })} /></label></>}
  </div>
}

export function HypothesisSetView({ value, artifact, status, onArtifact, artifacts }: { value: LabHypothesisSet; artifact?: string | null; status?: LabCampaign['hypothesis_set_status']; onArtifact: (hash: string) => void; artifacts: Record<string, LabArtifact> }) {
  return <>{status === 'needs_revalidation' && <p className="research-lab-warning">{t('researchLab.hypotheses.needsRevalidation')}</p>}<p className="idea-lab-note">{value.post_outcome ? t('researchLab.hypotheses.postOutcome') : t('researchLab.hypotheses.unverified')}</p><details className="idea-lab-section"><summary>{t('researchLab.hypotheses.saved', { count: value.candidates.length, revision: value.revision })}</summary>
    {value.candidates.map(item => <details key={item.id}><summary>{[...item.statement].slice(0, 120).join('')}{[...item.statement].length > 120 ? '…' : ''}</summary><p>{item.statement}</p><p><strong>{t('researchLab.hypotheses.scope')}: </strong>{item.scope || t('researchLab.hypotheses.unspecified')}</p>
      {(['assumptions', 'predictions', 'weakening_conditions'] as const).map(field => <div key={field}><strong>{t(`researchLab.hypotheses.${field}`)}</strong>{item[field].length ? <ul>{item[field].map((line, i) => <li key={i}>{line}</li>)}</ul> : <p>{t('researchLab.hypotheses.unspecified')}</p>}</div>)}
      {(['supporting_evidence', 'opposing_evidence'] as const).map(field => <div key={field}><strong>{t(`researchLab.hypotheses.${field}`)}</strong>{item[field].length ? item[field].map((ref, i) => <EvidenceView key={i} value={ref} onArtifact={onArtifact} artifacts={artifacts} />) : <p>{t('researchLab.hypotheses.noEvidence')}</p>}</div>)}
    </details>)}<p><strong>{t('researchLab.hypotheses.openAlternative')}: </strong>{value.open_alternative}</p>
    <details><summary>{t('researchLab.hypotheses.version')}</summary><p>{t('researchLab.hypotheses.briefVersion', { revision: value.brief_revision })}</p><p>{value.introduced_at}</p>{artifact && <><button className="quiet-button" onClick={() => onArtifact(artifact)}>{t('researchLab.hypotheses.readFrozen')}</button>{artifacts[artifact] && <pre className="idea-lab-source-text">{JSON.stringify(artifacts[artifact].content, null, 2)}</pre>}</>}{value.previous_artifact && <><button className="quiet-button" onClick={() => onArtifact(value.previous_artifact!)}>{t('researchLab.hypotheses.readPrevious')}</button>{artifacts[value.previous_artifact] && <pre className="idea-lab-source-text">{JSON.stringify(artifacts[value.previous_artifact].content, null, 2)}</pre>}</>}</details>
  </details></>
}
function EvidenceView({ value, onArtifact, artifacts }: { value: LabHypothesisEvidence; onArtifact: (hash: string) => void; artifacts: Record<string, LabArtifact> }) {
  return <details><summary>{t(`researchLab.hypotheses.ref.${value.kind}`)}</summary><p className="idea-lab-note">{t('researchLab.hypotheses.evidenceNotice')}</p><pre className="idea-lab-source-text">{JSON.stringify(value, null, 2)}</pre><button className="quiet-button" onClick={() => onArtifact(value.artifact)}>{t('researchLab.hypotheses.readEvidence')}</button>{artifacts[value.artifact] && <pre className="idea-lab-source-text">{JSON.stringify(artifacts[value.artifact].content, null, 2)}</pre>}</details>
}
