import type { LabCampaign, LabRound, LabSeed, LabExportBundle, LabProtocol, LabHypothesisSet } from './research-lab'

export const labHypothesisFixture = (): LabHypothesisSet => ({ id: 'campaign-one:hypotheses', revision: 1, brief_revision: 1, introduced_at: '2026-10-03T00:00:00Z', origin: 'human', post_outcome: false, previous_artifact: null, input_artifact: 'a'.repeat(64), scientific_status: 'not_validated', evidence_scope: 'Human-declared evidence links are not scientific validation.', candidates: [{ id: 'H1', statement: 'The qualification is limited to the supplied cases.', scope: 'This supplied note only.', assumptions: ['The supplied text has been transcribed correctly.'], predictions: ['The exact qualification occurs in this note.'], weakening_conditions: ['The qualification is absent from this note.'], supporting_evidence: [{ kind: 'source', source_id: 'source-one', artifact: 'a'.repeat(64), source_hash: 'c'.repeat(64), coverage: 'excerpt', missing_sections: ['Methods'] }], opposing_evidence: [] }], open_alternative: 'Omitted sections may change its applicability.', visible_evidence_refs: [{ kind: 'input', artifact: 'a'.repeat(64) }, { kind: 'source', source_id: 'source-one', artifact: 'a'.repeat(64), source_hash: 'c'.repeat(64), coverage: 'excerpt', missing_sections: ['Methods'] }] })

export const labProtocolFixture = (): LabProtocol => ({ id: 'planning-v0.5', title: 'Planning and frozen actions', content: 'Freeze rules before observation.', summary_version: 'implementation/1', is_full_source: false, scope: 'Local adapters only', summary_sha256: 'e'.repeat(64), source: { page_id: 'page_planning', url: 'https://chatgpt.com/space/page_planning', sequence: 2, updated_at: '2026-10-03T00:00:00Z', blocks: [{ id: 'block-one', hash: 'f'.repeat(64) }] } })
export const labExportFixture = (): LabExportBundle => ({ format: 'agentsdock-research-campaign/1', schema_version: 1, campaign_id: 'campaign-one', snapshot_kind: 'sqlite_read_transaction', data: { campaign: labFixture(), versions: [{ payload: labFixture() }], events: [], mutations: [{ response: labFixture() }], artifacts: [] }, manifest: { table_hashes: Object.fromEntries(['campaign', 'versions', 'events', 'mutations', 'artifacts'].map(key => [key, 'b'.repeat(64)])), authentication: 'content checksums only' }, bundle_sha256: 'c'.repeat(64) })

export const labFixture = (): LabCampaign => ({
  schema_version: 1, id: 'campaign-one', revision: 1, created_at: '2026-10-03T00:00:00Z', updated_at: '2026-10-03T00:00:00Z', entry: 'goal', status: 'planned',
  brief: { goal: 'Does the supplied text include the qualification?', hypothesis: '', success_criteria: 'Locate the exact quote and its context.', constraints: 'Supplied text only', revision: 1, authorized_actions: ['exact_quote', 'source_context'], stop_rules: ['End when bounded context is inspected.'] }, origin: null,
  adapter: { id: 'source_evidence', version: 'source_evidence/1', title: 'Supplied source evidence', task_family: 'source_evidence', methods: ['exact_quote', 'source_context'], input_schema: {}, observation_schema: {}, applicability: [], limitations: ['Quote occurrence does not validate a scientific claim'], required_protocols: [], execution: 'local_deterministic', fresh_replicates: false },
  input_artifact: 'a'.repeat(64), input_summary: { quote: 'Only these cases.' }, hypotheses: [],
  budget: { max_actions: 4, max_rounds: 3, used_actions: 0, reserved_actions: 0, remaining_actions: 4, model_tokens: 0, external_requests: 0, monetary_cost: 0, wall_ms: 0 },
  current_plan: { id: 'plan-one', round: 1, goal_revision: 1, input_artifact: 'a'.repeat(64), selected_action_id: 'action-one', selection_origin: 'policy', selection_reason: 'First eligible source', comparison_criteria: ['Source availability'], frozen_at: '2026-10-03T00:00:00Z', candidates: ['one', 'two'].map(id => ({ id: `action-${id}`, method: 'exact_quote', title: `Check exact quote: Source ${id}`, question: 'Does the exact quote occur?', goal_revision: 1, input_artifact: 'a'.repeat(64), parameters: { source_id: `source-${id}` }, expected_learning: 'Locate exact supplied evidence and expose missing context; assess no scientific implication', cost: { actions: 1, external_requests: 0, model_tokens: 0 }, qc_rules: ['Input content digest unchanged'], interpretation_rules: ['No scientific claim validation'], stop_rules: ['Source inspected'], adapter_version: 'source_evidence/1', protocol_refs: [], spec_artifact: 'b'.repeat(64) })) },
  rounds: [], decisions: [], claims: [], review: null, stop_reason: null, events: [], has_more_events: false,
})
export const labSeedFixture = (): LabSeed => ({ origin: { kind: 'idea', session_id: 'idea-one', generation_id: 'generation-one', selected_ids: ['direction-one'], decision_revision: 5 }, brief: { goal: 'Saved direction question', hypothesis: '', success_criteria: 'Check the frozen evidence.', constraints: '' }, inputs: { quote: 'Only these cases.', sources: [{ id: 'source-one', title: 'Source one', uri: 'supplied:one', text: 'Only these cases. The remaining cases are untested.', coverage: 'excerpt', missing_sections: ['Methods'], provenance: { source_hash: 'c'.repeat(64) } }] } })
export const labRoundFixture = (): LabRound => ({ index: 1, plan: labFixture().current_plan!, run: { id: 'run-one', attempt_id: 'attempt-one', generation: 1, status: 'completed', spec_artifact: 'b'.repeat(64), observation_artifact: 'd'.repeat(64), input_artifact: 'a'.repeat(64), replicate_id: null, is_independent_replicate: false, started_at: '2026-10-03T00:00:00Z', completed_at: '2026-10-03T00:00:01Z', usage: { actions: 1, model_tokens: 0 } }, observation: { kind: 'exact_quote', data: { exact_match_found: true, quote: 'Only these cases.', match_count: 1, source_id: 'source-one' }, coverage: { kind: 'excerpt', missing_sections: ['Methods'] } }, qc: { passed: true, checks: [{ name: 'integrity', passed: true, detail: 'Frozen input unchanged' }] }, analysis: { claim: 'The exact quote occurs once.', source_support: 'supported', inference_validity: 'cannot_determine', limitations: ['Quote occurrence does not validate a scientific claim'], input_refs: [] }, review: { next_action: 'continue', reason: 'The quote was found; inspect surrounding qualifications before any interpretation', next_method: 'source_context', uncertainties: ['Scientific meaning and inference remain unassessed'], alternatives: ['Stop unresolved'], input_refs: [] } })
